# Configuración de VerifBuild
# Autor: DarkovDev

# Tiempo de verificación general (en segundos)
time: 100

# Mensajes del plugin
messages:
  activated: "&a¡Área de verificación activada! Construye la estructura requerida."
  completed: "&b¡Estructura verificada correctamente! Recompensa entregada."
  deactivated: "&e¡Área de verificación desactivada!"
  no-permission: "&cNo tienes permiso para usar este tipo de verificación."
  max-uses-reached: "&cEste tipo de verificación ha alcanzado su límite de usos."
  expired: "&c¡El tiempo ha expirado! El área fue cancelada y se te ha devuelto el bloque."

# Configuración de verificaciones
verifications:
  # Casa básica
  basic_house:
    trigger-block: EMERALD_BLOCK
    area-x: 5
    area-y: 5
    area-z: 5
    max-uses: 10
    time: 100 # Tiempo personalizado para esta estructura (en segundos)
    structure:
      OAK_PLANKS: 1
    on-success:
      relative-pos: "0,1,0"
      commands:
        - "give %player% diamond 5"
        - "xp add %player% 100"
    on-interact:
      commands:
        - "say %player% ha interactuado con el bloque verificador de casa básica"

  # Herrería
  blacksmith:
    trigger-block: ANVIL
    area-x: 4
    area-y: 4
    area-z: 4
    max-uses: 5
    # No tiene tiempo personalizado, usará el general
    structure:
      COBBLESTONE: 15
      FURNACE: 2
      CRAFTING_TABLE: 1
      ANVIL: 1
      CHEST: 1
    on-success:
      relative-pos: "0,0,0"
      commands:
        - "give %player% iron_ingot 32"
        - "give %player% coal 64"
    on-interact:
      commands:
        - "say %player% ha interactuado con el bloque verificador de herrería"

  # Altar mágico
  magic_altar:
    trigger-block: ENCHANTING_TABLE
    area-x: 3
    area-y: 3
    area-z: 3
    max-uses: 3
    structure:
      BOOKSHELF: 8
      OBSIDIAN: 4
      DIAMOND_BLOCK: 1
      ENCHANTING_TABLE: 1
    on-success:
      relative-pos: "0,0,0"
      commands:
        - "give %player% experience_bottle 16"
        - "give %player% lapis_lazuli 64"
        - "effect give %player% night_vision 600"
    on-interact:
      commands:
        - "say %player% ha interactuado con el bloque verificador de altar mágico"

  # Granja automática
  auto_farm:
    trigger-block: DISPENSER
    area-x: 6
    area-y: 4
    area-z: 6
    max-uses: -1
    structure:
      HOPPER: 4
      DISPENSER: 2
      REDSTONE_BLOCK: 2
      CHEST: 2
      WATER: 1
      FARMLAND: 16
    on-success:
      relative-pos: "0,1,0"
      commands:
        - "give %player% bone_meal 64"
        - "give %player% wheat_seeds 32"
        - "give %player% carrot 16"
        - "give %player% potato 16"
    on-interact:
      commands:
        - "say %player% ha interactuado con el bloque verificador de granja automática"