name: VerifBuild
version: '${project.version}'
main: me.verifbuild.VerifBuild
api-version: '1.20'
author: DarkovDev
description: ${project.description}
softdepend: [PlaceholderAPI]

commands:
  verifbuild:
    description: Comando principal de VerifBuild
    usage: /verifbuild [list|reload|give <tipo>]
    aliases: [vb]
    permission: verifbuild.admin
  give:
    description: Da un bloque verificador al jugador
    usage: /give <jugador> <tipo>
    permission: verifbuild.give

permissions:
  verifbuild.admin:
    description: Permite usar todos los comandos administrativos
    default: op
    children:
      verifbuild.use.*: true
      verifbuild.cancel.*: true
      verifbuild.list: true
      verifbuild.reload: true
      verifbuild.give: true
  verifbuild.use.*:
    description: Permite usar cualquier tipo de verificación
    default: op
  verifbuild.cancel.*:
    description: Permite cancelar cualquier verificación
    default: op
  verifbuild.list:
    description: Permite ver las verificaciones activas
    default: op
  verifbuild.reload:
    description: Permite recargar la configuración
    default: op
  verifbuild.give:
    description: Permite dar bloques verificadores
    default: op
